name: Web build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      uses: Jaid/action-npm-install@v1.2.4
      with:
        working-directory: ${{ env.wd }}
        packageManager: npm
          # Runs a set of commands using the runners shell
    - name: Create .env
      working-directory: ${{ env.wd }}
      run: |
        echo MAPLIGHT=${{ secrets.MAPBOX_STYLE }} > .env
        echo MAPBOX_KEY=${{ secrets.MAPBOX_KEY }} >> .env
        echo REST_URL=${{ secrets.REST_URL }} >> .env
        echo AUTH_URL=${{ secrets.AUTH_URL }} >> .env
        echo EMAIL=${{ secrets.HELP_MAIL }} >> .env
        echo EMAIL_USER_ID=${{ secrets.HELP_USERID }} >> .env
        echo EMAIL_SERVICE_ID=${{ secrets.HELP_SERVICEID }} >> .env
    - name: Build
      working-directory: ${{ env.wd }}
      run: npm run build
