name: Publish Android app to Google Play Store

on:
  push:
    branches:
      - mobileci
    paths:
      - "src/Mobile/carpool/**"
      - ".github/workflows/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
